## Tarea #1 (Grupos de dos integrantes)

## Estudiantes: Nayely Márquez y Fabián Parra

Crear un ambiente de trabajo (.ipynb) basado en PYTHON3 y llamarle Tarea-1.ipynb, además debe contener
las librerías: numpy, matplotlib, scikit-learn, pandas, jupyter notebook como mínimo, puede agregar las que considere necesario. El objetivo de esta Tarea 1 consiste en normalizar y estandarizar el set
de datos de daily-min-temperatures.csv de forma manual y automática a partir de scikit-learn
o la librería que considere apropiada. El entregable consiste en el url de la notebook Tarea-1.ipynb en
GITHUB. Subir al TEC Digital un archivo .txt simple con el url a más tardar el dia acordado en clase e
indicado en el TEC Digital, envíos pasado el limite de entrega se aplicaría la penalización discutida en clase.

In [1]:
#!pip install sklearn 
import torch as torch
import numpy as np
import matplotlib as plt
import sklearn  
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn import preprocessing

Primero se cargan los datos, luego se elige la columna de temperatura, ya que el año no nos intereza para la normalización y estandarización. 

In [2]:
df = pd.read_csv(
    'D:/50688/Fabian/TEC/Aprendizaje Automatico/Tarea 1/daily-min-temperatures.txt', sep=",",header=0)


d=df.iloc[:,1]
print(d)
d=np.array(d)

0       20.7
1       17.9
2       18.8
3       14.6
4       15.8
        ... 
3645    14.0
3646    13.6
3647    13.5
3648    15.7
3649    13.0
Name: Temp, Length: 3650, dtype: float64


Primero se va a realizar la **estandarización** calculando:

$$y = (x - mean) / StandardDeviation$$

Se hace un reshape para poder utilizar la función sin problemas.

In [3]:
X_train= np.reshape(d, (-1, 1))

scaler = preprocessing.StandardScaler().fit(X_train)
scaler


scaler.mean_


scaler.scale_


X_scaled = scaler.transform(X_train)
X_scaled

array([[2.33888328],
       [1.65113873],
       [1.87219948],
       ...,
       [0.5703973 ],
       [1.11076801],
       [0.44758577]])

Se realiza el calculo manual, restandole la media a los datos y dividiendo entre la desviación estándar.

In [4]:
d_estand_m = (X_train - X_train.mean()) / X_train.std()
print(d_estand_m)

[[2.33888328]
 [1.65113873]
 [1.87219948]
 ...
 [0.5703973 ]
 [1.11076801]
 [0.44758577]]


Para la **normalización** se realiza el calculo:
    
$$y = (x - min) / (max - min)$$

Primero se utiliza la función:

In [5]:
A = X_train

min_max_scaler = preprocessing.MinMaxScaler()   

A = min_max_scaler.fit_transform(A)
print(A)

[[0.78707224]
 [0.68060837]
 [0.7148289 ]
 ...
 [0.51330798]
 [0.59695817]
 [0.49429658]]


Manualmente se resta el mínimo y se divide entre la resta del valor máximo y mínimo.

In [6]:
A = X_train

d_norm_m=(A-A.min(axis=0))/(A.max(axis=0) - A.min(axis=0))

d_norm_m

array([[0.78707224],
       [0.68060837],
       [0.7148289 ],
       ...,
       [0.51330798],
       [0.59695817],
       [0.49429658]])